# DiploDatos 2026- Mentoría "Deteccion de fraude: ¿Como cuido a mis clientes? Machine Learning aplicado a un caso de negocio financiero"

## <font color=blue> Trabajo Practico N° 1 

##  Mentoría "Deteccion de fraude: ¿Como cuido a mis clientes? Machine Learning aplicado a un caso de negocio financiero"

## Analisis y Visualizacion de Datos (EDA)
### Entregable

● Los invito a desarrollar cada punto en la Notebook compartida que les sirve de guía para cumplir con este TP.

● Se debe subir el entregable a un repositorio GitHub o enviar el link a un Google Colab.

● Si bien seguramente se harán muchos análisis de diversos tipos y consideraciones, solo se debe dejar en la Notebook a entregar aquellos análisis que sean relevantes y que consideren de importancia según el tema a presentar.

● Recuerden siempre que luego de cada gráfico, cálculo, es importante describir brevemente que es lo que se está haciendo, y si son gráficos, a que conclusión han llegado, para expresar los comprendido y el nivel de profundidad alcanzada de los contenidos teóricos impartidos.

## 1.	Familiarización con el dataset:

Para ello se deberá interpretar la documentación brindada donde se detalle el significado de cada variable, posteriormente se deberá importar los datos, analizar su estructura, tipos de campos, ver si hay datos faltantes.

## 2.	Interpretando el dataset
¿Qué tipo de variables tenemos?, categóricas, numéricas, discretas, continuas?  

Brindar los estadisticos descriptivos, media, mediana, percentiles, de comentarios de los mismos.

¿Hay clientes duplicados?, ¿Hay datos nulos? ¿A qué se puede deber? 

¿Hay outliers?  ¿A qué se puede deber?

## 3.	Análisis y Visualización de los datos

Para un buena predicción/segmentación es necesario realizar un buen análisis descriptivo, exploración de los datos considerando su tipo y valores definidos y tener acabado conocimiento de que representa cada uno de ellos.

Para los datos numéricos realizar una breve descripción de los mismos, analizando sus medias, percentiles, outliers. 
Mientras que para las variables categóricas realizar un análisis de transaccionalidad vrs Rubro, Estado Civil, Sexo, Edad, Activolataforma, etc. Realizar un análisis de variabilidad de la transaccionalidad respecto de estas variables para cada Clase (Es Fraude / No es Fraude)y otras más que puedan considerar de utilidad para el entendimiento del comportamiento del cliente, dado que esto nos ayudara en nuestro modelo de deteccion de anomalias y asi mitigar el fraude al detectarlo con atelacion.

Algunas de las preguntas que nos podríamos realizar son las siguientes:

¿A qué fecha son los datos? ¿Fue correcto la selección de este periodo para el análisis? ¿Contamos con suficientes datos para llevar a cabo esa prediccion?

¿Hay datos nulos? ¿Hay OutLiers? Identificar valores atipicos y nulos.

¿Hay datos duplicados? ¿Cuantos clientes tenemos en nuestro dataset?

¿Como es la distribucion del dato Trx_Importe? ¿Es necesario considerar por moneda (pesos/dolar)? De un comentario al respecto.

¿Al dato Trx_RubroRed, ¿cómo lo consideramos? Discreto o Continuo? Grafique su distribucion y de breve comentario.

¿Existe algún tipo de relación entre Rubro_Red, Trx_terminalRed , Trx_CiudadTerminal?

¿Con que frecuencia realiza las compras? Dia de la semana, dia del mes. Ejemplo, compra todos los lunes, compra todos los 1 de cada mes.

¿Que tiempo transcurre entre transacciones? 

¿Que rubros son los mas frecuentes? 

¿Que rubros son los que mas importe gastan los clientes?

¿Cuales son los horarios de compras habituales de los clientes? 

¿Qué tipo de movimiento se realiza más? Transferencia, compra, pago de impuesto, etc.

¿El cliente estuvo presente en la compra?

¿Cuál es el importe promedio gastado para ciertos días en ciertos rubros de comercio?

¿Como se encuentran las clases Fraude / No Fraude, estan balanceadas? (¿Hay mas transacciones No Fraudulentas que Fraudulentas? o viceversa)
Comparar el comportamiento de las transacciones Fraudulentas vrs No Fraudulentas, se puede comparar:
    Hora del dia
    Dia de la semana
    Frecuencia entre que ocurren 
    Tipo de movimiento (Compra en pesos o compra extranjera)
    Tipo Terminal utilizada , IdTerminal utilizada
    Ciudad de la transaccion
    Rubro de Compra 
    Hacer un comparativo de Rubro , Ciudad 
    Tiempo transcurrido entre transacciones 
    Cuales son los rubros mas populares

Basándose en los análisis anteriores, realice una matriz de correlacion entre las variables y la variable target.

Puede ya definir cuales serán las variables mas interesantes que contribuirán al modelo.

# Importar librerías necesarias

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stat
import scipy.stats as st
from statistics import stdev
from scipy.stats import t
import datetime
#import missingno as msno
import seaborn

seaborn.set_context('talk')
sns.set_context('talk')

# Seteo de displays
pd.set_option('display.max_columns',10000)
pd.set_option('display.max_rows',10000)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
pd.options.display.max_columns = None # para que no recorte las columnas

# Leer el dataset

In [3]:
# Importamos el datset que definimmos

df = pd.read_csv ("muestra.del", sep='|', encoding='latin-1')

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192664 entries, 0 to 192663
Data columns (total 26 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Cliente_Id                192664 non-null  int64
 1   Cliente_Sexo              160022 non-null  object
 2   Cliente_FechaNacimiento   192664 non-null  object
 3   Cliente_EstadoCivil       160022 non-null  object
 4   Cliente_CodigoPostal      192664 non-null  int64
 5   Cliente_ActivoPlataforma  192664 non-null  object
 6   Cliente_Segmento          160022 non-null  object
 7   Cuenta_Producto           192664 non-null  object
 8   Movimiento_Tipo           192664 non-null  object
 9   Movimiento_Agrupa         192664 non-null  object
 10  Movimiento_SubAgrup       192664 non-null  object
 11  Movimiento_Codigo         192664 non-null  int64
 12  Trx_RedLogicaTerminal     192664 non-null  object
 13  Trx_Rta                   192664 non-null  object
 14  Trx_TipoTerminal          192664 non-null  int64
 15  Trx_TerminalRed           192664 non-null  object
 16  Trx_RubroRed              192664 non-null  int64
 17  Trx_CiudadTerminal        186943 non-null  object
 18  Trx_ModoIngreso           192664 non-null  object
 19  Trx_EsChip                192664 non-null  object
 20  Trx_Estado                192664 non-null  object
 21  Trx_Fecha                 192664 non-null  int64
 22  Trx_Hora                  192664 non-null  int64
 23  Trx_Moneda                192664 non-null  int64
 24  Trx_Importe               192664 non-null  object
 25  Es_Fraude                 192664 non-null  object
dtypes: int64(8), object(18)
memory usage: 38.2+ MB
None

In [5]:
df.head()

,Cliente_Id,Cliente_Sexo,Cliente_FechaNacimiento,Cliente_EstadoCivil,Cliente_CodigoPostal,Cliente_ActivoPlataforma,Cliente_Segmento,Cuenta_Producto,Movimiento_Tipo,Movimiento_Agrupa,Movimiento_SubAgrup,Movimiento_Codigo,Trx_RedLogicaTerminal,Trx_Rta,Trx_TipoTerminal,Trx_TerminalRed,Trx_RubroRed,Trx_CiudadTerminal,Trx_ModoIngreso,Trx_EsChip,Trx_Estado,Trx_Fecha,Trx_Hora,Trx_Moneda,Trx_Importe,Es_Fraude
0,19,NaN,6/12/1948,NaN,5021,Si,NaN,CajaAhorro,D,A11,SA06,1050,C,SI,11,4231303838303233,5969,CAPITAL FEDER,A,N,A,250820,10473300,1,"35999,98",NO
1,19,MASCULINO,6/12/1948,CASADO/A,5021,Si,S2,CajaAhorro,D,A11,SA06,1050,C,SI,0,3645394244463336,5499,CORDOBA,F,S,A,251014,12284100,1,"33000,00",NO
2,19,MASCULINO,6/12/1948,CASADO/A,5021,Si,S2,CajaAhorro,D,A01,SA03,1040,B,SI,1,NO APLICA,-1,CORDOBA,E,S,A,251111,18401316,1,"100000,00",NO
3,19,MASCULINO,6/12/1948,CASADO/A,5021,Si,S2,CajaAhorro,D,A11,SA06,1050,C,SI,11,4231303838303233,5969,CAPITAL FEDER,A,N,A,251022,10163200,1,"35999,99",NO
4,19,MASCULINO,6/12/1948,CASADO/A,5021,Si,S2,CajaAhorro,D,A11,SA06,1050,C,SI,7,3535443543393239,4899,CABA,A,N,A,251101,7150400,1,"24158,49",NO

In [6]:
df.describe()

,Cliente_Id,Cliente_CodigoPostal,Movimiento_Codigo,Trx_TipoTerminal,Trx_RubroRed,Trx_Fecha,Trx_Hora,Trx_Moneda
count,192664.000000,192664.000000,192664.000000,192664.000000,192664.000000,192664.000000,192664.000000,192664.000000
mean,378.335558,4908.238628,1042.545660,3.618979,2741.333944,250670.103356,14346534.861220,1.031038
std,203.380774,973.622041,8.538547,3.839279,3099.142471,340.151337,5109833.482483,0.173422
min,1.000000,1013.000000,1010.000000,0.000000,-1.000000,250101.000000,0.000000,1.000000
25%,217.000000,5000.000000,1038.000000,0.000000,-1.000000,250403.000000,11010600.000000,1.000000
50%,378.000000,5004.000000,1049.000000,3.000000,-1.000000,250704.000000,14033316.500000,1.000000
75%,543.000000,5194.000000,1050.000000,7.000000,5462.000000,251001.000000,18554000.000000,1.000000
max,757.000000,6275.000000,1065.000000,12.000000,9399.000000,251231.000000,23595935.000000,2.000000